### PR TITLE
Add visible flag to versions collection

### LINKED ISSUE #399: Add "visible" field to "versions" collection with default value "true"
In order to allow `soft-deletes` a `visible` flag should be added to the `versions` collection.  
If code in the sdkman/sdk-candidates project breaks due to the schema change, it should  be fixed in a way to stay backwards-compatible (i.e. no visible change to the behaviour).

This is the first step in resolving #170.

### PR DESCRIPTION
**Pull request by helpermethod**
Fixes sdkman/sdkman-db-migrations#399.

### CODE REVIEW

**Review by marc0der — COMMENTED** [review]
Great stuff! Would you mind if we also test the other two explicit scenarios?

**Comment by helpermethod** [comment]
Sure! But what are the other *two* scenarios? ~~I can only think of one (visible set to `false`).~~

**EDIT**
Hm, probably something like

visible => true
visible => false
visible => field does not exist

**Comment by helpermethod** [comment]
Hm, I'm wondering if `insertVersion` and `insertVersions` should actually allow setting the  `visibility` flag. May that should only be possible by something like 

```scala
def hideVersion(candidate: String, version: String, platform: String) =
  versionsCollection
    .updateOne(
      and(equal("candidate", candidate), equal("version", version), equal("platform", platform)),
       set("visible", Some(false))
    )
    .results()
```

**Comment by vibin** [comment]
@marc0der hi, is this deployed? i.e. are older JDK versions being maintained now? thanks!

**Comment by helpermethod** [comment]
Hi @vibin,

there is still some work to do but expect the feature to go live very soon!

**Comment by vibin** [comment]
@helpermethod sure, thank you :)

**Pull request merged**
